//
// Created by Mbocco on 28/5/2024.
//

#ifndef UCC_PROYECTOFINAL_ALFEI_CARRIZO_BOCCO_MAIN_H
#define UCC_PROYECTOFINAL_ALFEI_CARRIZO_BOCCO_MAIN_H


class main {

};


#endif //UCC_PROYECTOFINAL_ALFEI_CARRIZO_BOCCO_MAIN_H
